export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";